stages:
    - deploy

test:
    stage: deploy
    script:
        - pwd
        - whoami
        - source /home/tsogjavkhlan_odbayar/interviewer/interviewer/bin/activate
        - nohup streamlit run interviewer.py
    only:
        - main